"""CSES problem statement parser.

CSES generates <h1 id="example"> or <h1 id="exampleN"> headings containing sample input/output
content inline with the problem statement. This duplicates the structured test data stored in
tests/, so the Example section is stripped during normalization. Before stripping, the sample
content is harvested from every example heading.
"""

import re
from typing import override

from bs4 import BeautifulSoup
from bs4.element import Tag

from ...cp_metadata import MathSentinelRegistry, SampleCase, parse_memory_limit, parse_time_limit
from ..lib import BaseParser, extract_math_nodes

_EXAMPLE_ID_RE = re.compile(r"^example\d*$")


def _extract_cses_samples(soup: BeautifulSoup) -> list[SampleCase]:
    examples = soup.find_all("h1", id=_EXAMPLE_ID_RE)
    if not examples:
        return []

    all_samples: list[SampleCase] = []
    all_to_remove: list[Tag] = []

    for example in examples:
        to_remove: list[Tag] = [example]
        pres: list[Tag] = []

        for sibling in example.find_next_siblings():
            if sibling.name == "h1":
                break
            to_remove.append(sibling)
            if sibling.name == "pre":
                pres.append(sibling)

        all_samples.extend(
            SampleCase(input=pres[i].get_text(), output=pres[i + 1].get_text()) for i in range(0, len(pres) - 1, 2)
        )
        all_to_remove.extend(to_remove)

    for node in all_to_remove:
        node.decompose()
    return all_samples


class CsesParser(BaseParser):
    """Parser for CSES problem statements. Strips the autogenerated Example section."""

    site: str = "cses"
    platform: str = "CSES"
    selector: str = "div.md"
    _strip_trailing: bool = False

    @override
    def extract_name(self, soup: BeautifulSoup) -> str | None:
        if soup.title and soup.title.get_text(strip=True):
            title = soup.title.get_text(strip=True)
            if title.startswith("CSES - "):
                return title.removeprefix("CSES - ").strip()
            return title
        h1 = soup.find("h1")
        if h1 is not None:
            return h1.get_text(strip=True)
        return None

    @override
    def extract_limits(self, soup: BeautifulSoup) -> tuple[float | None, int | None]:
        constraints = soup.select_one("ul.task-constraints")
        if constraints is None:
            return None, None
        time_limit: float | None = None
        memory_limit: int | None = None
        for li in constraints.find_all("li"):
            text = li.get_text(strip=True)
            label, _, value = text.partition(":")
            label_lower = label.strip().lower()
            if label_lower == "time limit":
                time_limit = parse_time_limit(value)
            elif label_lower == "memory limit":
                memory_limit = parse_memory_limit(value)
        return time_limit, memory_limit

    @override
    def normalize(self, soup: BeautifulSoup, name: str | None = None) -> tuple[MathSentinelRegistry, list[SampleCase]]:
        samples = _extract_cses_samples(soup)
        return extract_math_nodes(soup), samples
